# Generated by Django 2.2 on 2019-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=50, verbose_name='host')),
                ('lan_ip', models.CharField(default='', max_length=50, verbose_name='lan_ip')),
                ('uuid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('os_name', models.CharField(default='', max_length=50, verbose_name='os_name')),
                ('published_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
