# Generated by Django 2.2 on 2019-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinfo',
            options={'verbose_name': 'Service Information', 'verbose_name_plural': 'Service Information'},
        ),
    ]
