# Generated by Django 2.2 on 2019-04-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190412_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceInfo',
            new_name='DeviceInfo',
        ),
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': 'Device Information', 'verbose_name_plural': 'Device Information'},
        ),
    ]
