# Generated by Django 2.2 on 2019-04-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190412_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='lan_ip',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
