# Generated by Django 2.2 on 2019-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190414_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('published_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Humidity',
                'verbose_name_plural': 'Device Humidity',
            },
        ),
        migrations.CreateModel(
            name='DeviceLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('light', models.FloatField(blank=True, default=None, null=True)),
                ('published_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Light',
                'verbose_name_plural': 'Device Light',
            },
        ),
        migrations.CreateModel(
            name='DeviceTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('temperature', models.FloatField(blank=True, default=None, null=True)),
                ('published_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Temperature',
                'verbose_name_plural': 'Device Temperature',
            },
        ),
    ]
