# Generated by Django 2.2 on 2019-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_devicehumidity_devicelight_devicetemperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicehumidity',
            options={'verbose_name': 'Humidity', 'verbose_name_plural': 'Humidity'},
        ),
        migrations.AlterModelOptions(
            name='devicelight',
            options={'verbose_name': 'Light', 'verbose_name_plural': 'Light'},
        ),
        migrations.AlterModelOptions(
            name='devicetemperature',
            options={'verbose_name': 'Temperature', 'verbose_name_plural': 'Temperature'},
        ),
        migrations.RemoveField(
            model_name='devicehumidity',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='devicelight',
            name='light',
        ),
        migrations.RemoveField(
            model_name='devicetemperature',
            name='temperature',
        ),
        migrations.AddField(
            model_name='devicehumidity',
            name='timestamp',
            field=models.IntegerField(default=0, verbose_name='detected time'),
        ),
        migrations.AddField(
            model_name='devicehumidity',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='humidity'),
        ),
        migrations.AddField(
            model_name='devicelight',
            name='timestamp',
            field=models.IntegerField(default=0, verbose_name='detected time'),
        ),
        migrations.AddField(
            model_name='devicelight',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='light'),
        ),
        migrations.AddField(
            model_name='devicetemperature',
            name='timestamp',
            field=models.IntegerField(default=0, verbose_name='detected time'),
        ),
        migrations.AddField(
            model_name='devicetemperature',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='temperature'),
        ),
    ]
