# Generated by Django 2.2 on 2019-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190415_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='allow',
            field=models.BooleanField(default=True),
        ),
    ]
