# Generated by Django 2.2 on 2019-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_deviceinfo_allow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='uuid',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='uuid'),
        ),
    ]
